version: '3.7'

networks:
  monitor-net:
    driver: bridge
  ingress:
    external: true

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.13.1
    labels:
      - org_label_schema.group=monitoring
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
  blackbox:
    image: prom/blackbox-exporter
    labels:
      - org_label_schema.group="monitoring"
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./blackbox:/config
    command:
      - '--config.file=/config/blackbox.yml'
    expose: 
      - 9115
    extra_hosts:
      - monitor.hola.com:${HOST_IP}
      - wiki.hola.com:${HOST_IP}
      - wp.hola.com:${HOST_IP}
      - cloud.hola.com:${HOST_IP}
    networks:
      - monitor-net
      - ingress
  alertmanager:
    image: prom/alertmanager:v0.19.0
    labels:
      - org_label_schema.group=monitoring
    restart: unless-stopped
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus
    expose:
      - 9093
    networks:
      - monitor-net
  nodeexporter:
    image: prom/node-exporter:v0.18.1
    labels:
      - org_label_schema.group=monitoring
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitor-net
  pushgateway:
    image: prom/pushgateway:v1.0.0
    labels:
      - org_label_schema.group=monitoring
    restart: unless-stopped
    depends_on:
      - prometheus
    expose:
      - 9091
    networks:
      - monitor-net
  cadvisor:
    image: google/cadvisor:v0.33.0
    labels:
      - org_label_schema.group=monitoring
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:6.3.6
    labels:
      - org_label_schema.group=monitoring
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      - GF_SERVER_ROOT_URL=https://monitor.hola.com
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net

  web:
    build: ./nginx
    labels:
      - traefik.enable=true
      - traefik.docker.network=ingress
      - traefik.port=80
      - traefik.frontend.rule=Host:monitor.hola.com,prometheus.hola.com,alert.hola.com
      - traefik.backend=monitor
      - org_label_schema.group=monitoring
    restart: unless-stopped
    volumes:
      - ./nginx/.htpasswd:/.htpasswd
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    depends_on:
      - grafana
      - prometheus
      - alertmanager
    networks: 
      - ingress
      - monitor-net